version: 2
registries:
  onshopfront:
    type: "npm-registry"
    url: "https://npm.pkg.github.com"
    token: "${{secrets.DEPENDABOT_TOKEN}}"
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@onshopfront/*"
    registries: "*"
    labels:
      - "dependencies"
